# 1. Get Structured data from reviews

In [1]:
#Feature Extraction
#Extract some 2/3-grams phrases 
#Foods and service

In [1]:
import pandas as pd
file = pd.read_csv("./Chinese_review.csv")

In [2]:
file

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  business_index  \
0                0             0               0               0   
1                1             1               1               0   
2                2             2               2               0   
3                3             3               3               0   
4                4             4               4               0   
5                5             5               5               0   
6                6             6               6               0   
7                7             7               7               0   
8                8             8               8               0   
9                9             9               9               0   
10              10            10              10               0   
11              11            11              11               0   
12              12            12              12               0   
13              13            13              13               0   
14              14            14              14               0   
15              15            15              15               0   
16              16            16              16               0   
17              17            17              17               0   
18              18            18              18               0   
19              19            19              19               0   
20              20            20              20               0   
21              21            21              21               0   
22              22            22              22               0   
23              23            23              23               0   
24              24            24              24               0   
25              25            25              25               0   
26              26            26              26               0   
27              27            27              27               0   
28              28            28              28               0   
29              29            29              29               0   
...            ...           ...             ...             ...   
261536      261536        261536          261536            4431   
261537      261537        261537          261537            4431   
261538      261538        261538          261538            4431   
261539      261539        261539          261539            4431   
261540      261540        261540          261540            4431   
261541      261541        261541          261541            4431   
261542      261542        261542          261542            4431   
261543      261543        261543          261543            4431   
261544      261544        261544          261544            4431   
261545      261545        261545          261545            4431   
261546      261546        261546          261546            4431   
261547      261547        261547          261547            4431   
261548      261548        261548          261548            4431   
261549      261549        261549          261549            4431   
261550      261550        261550          261550            4432   
261551      261551        261551          261551            4432   
261552      261552        261552          261552            4432   
261553      261553        261553          261553            4432   
261554      261554        261554          261554            4432   
261555      261555        261555          261555            4432   
261556      261556        261556          261556            4432   
261557      261557        261557          261557            4432   
261558      261558        261558          261558            4432   
261559      261559        261559          261559            4432   
261560      261560        261560          261560            4432   
261561      261561        261561          261561            4432   
261562      261562        261562          261562            4433

In [2]:
#24 2-grams phrases
phrases_2 = [('dim','sum'), ('fried','rice'), ('orange', 'chicken'), ('chow', 'mein'), ('pad', 'thai'), ('sour', 'soup'), ('hot', 'pot'), ('spring', 'rolls'), ('lo', 'mein'), ('bbq', 'pork'), ('mongolian', 'beef'), ('egg', 'roll'), ('wonton', 'soup'), ('soy', 'sauce'), ('ice', 'cream'), ('pork', 'belly'), ('milk', 'tea'), ('fried', 'chicken'),  ('sour', 'chicken'), ('white', 'rice'), ('sesame', 'chicken'), ('chicken', 'wings'), ('peking', 'duck'), ('bubble', 'tea')]

In [3]:
#10 3-grams phrases
phrases_3 = [('egg', 'drop', 'soup'), ('beef', 'noodle', 'soup'), ('kung', 'pao', 'chicken'), ('chicken', 'fried', 'rice'), ('pork', 'fried', 'rice'), ('black', 'bean', 'sauce'), ('shrimp', 'fried', 'rice'), ('xiao', 'long', 'bao'), ('egg', 'foo', 'young'), ('dan', 'dan', 'noodles')]

In [5]:
len(phrases_3)

10

In [5]:
#88183 has keyword "service"
data_service = []
for i in file["text_token"]:
    if "service" in i:
        data_service.append(1)
    else:
        data_service.append(0)

In [6]:
#read the csv get the string, thus convert the string to list
import ast
bigram = file["bigram"]
bigram_token = bigram.tolist()
bigram_token = [ast.literal_eval(review) for review in bigram_token]

In [7]:
trigram = file["trigram"]
trigram_token = trigram.tolist()
trigram_token = [ast.literal_eval(review) for review in trigram_token]

In [8]:
#data of phrases
data_phrases_2 = []

for i in bigram_token:
    score = []
    for phrase in phrases_2:
        if phrase in i:
            score.append(1)
        else:
            score.append(0)
    
    data_phrases_2.append(score)
    
data_phrases_3 = []

for i in trigram_token:
    score = []
    for phrase in phrases_3:
        if phrase in i:
            score.append(1)
        else:
            score.append(0)
    
    data_phrases_3.append(score)

In [9]:
#combine the data
#100 thousands data are all zero
data = []
length = len(data_service)
for i in range(0, length):
    score = []
    score = [data_service[i]] + data_phrases_2[i] + data_phrases_3[i]
    data.append(score)

In [10]:
#indentify if "dimsum" in the review
for i in range(0,len(data)):
    if "dimsum" in file["text_token"][i]: data[i][1] = 1
    

# 2. Fit all data in different Classifier

In [13]:
#fit in the linear regression
import numpy as np
from sklearn.linear_model import LinearRegression

In [14]:
X = np.array(data)
Y = file["stars"]

In [15]:
m = LinearRegression().fit(X,Y)

In [16]:
m.score(X,Y)

0.006957340279816759

In [17]:
m.intercept_

3.502259816282746

In [116]:
m.coef_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [19]:
name = ["service"] + phrases_2 + phrases_3
print(name)

['service', ('dim', 'sum'), ('fried', 'rice'), ('orange', 'chicken'), ('chow', 'mein'), ('pad', 'thai'), ('sour', 'soup'), ('hot', 'pot'), ('spring', 'rolls'), ('lo', 'mein'), ('bbq', 'pork'), ('mongolian', 'beef'), ('egg', 'roll'), ('wonton', 'soup'), ('soy', 'sauce'), ('ice', 'cream'), ('pork', 'belly'), ('milk', 'tea'), ('fried', 'chicken'), ('sour', 'chicken'), ('white', 'rice'), ('sesame', 'chicken'), ('chicken', 'wings'), ('peking', 'duck'), ('bubble', 'tea'), ('egg', 'drop', 'soup'), ('beef', 'noodle', 'soup'), ('kung', 'pao', 'chicken'), ('chicken', 'fried', 'rice'), ('pork', 'fried', 'rice'), ('black', 'bean', 'sauce'), ('shrimp', 'fried', 'rice'), ('xiao', 'long', 'bao'), ('egg', 'foo', 'young'), ('dan', 'dan', 'noodles')]


In [20]:
index = []
for i in range(0,35):
    if m.coef_[i] < -0.2 :
        index.append(i)
print(index)
print([name[i] for i in index])

[12, 14, 20]
[('egg', 'roll'), ('soy', 'sauce'), ('white', 'rice')]


In [21]:
#fit in the logistic regression
from sklearn.linear_model import LogisticRegressionCV

In [22]:
clf = LogisticRegressionCV(cv=5, random_state=0,multi_class='multinomial').fit(X, Y)

In [23]:
clf.coefs_paths_

{1.0: array([[[-2.04139051e-02, -6.77440578e-02, -3.12997566e-02, ...,
           4.45617948e-04, -7.01235435e-03, -2.13623190e-01],
         [-4.22962774e-02, -2.55350087e-01, -1.08045670e-01, ...,
           4.18057860e-03, -4.96561407e-02, -1.71458308e-01],
         [-4.53450770e-02, -4.19089396e-01, -1.58514351e-01, ...,
           3.39798961e-02, -2.52595501e-01, -1.24265347e-01],
         ...,
         [-4.45006779e-02, -4.67716532e-01, -1.77431830e-01, ...,
           1.46067039e-01, -9.46643176e-01, -9.63728511e-02],
         [-4.44978140e-02, -4.67727323e-01, -1.77436644e-01, ...,
           1.46067966e-01, -9.46689563e-01, -9.63549466e-02],
         [-4.45005272e-02, -4.67731514e-01, -1.77438972e-01, ...,
           1.46068247e-01, -9.46704900e-01, -9.63590227e-02]],
 
        [[-1.30729855e-02, -6.68423736e-02, -3.41310246e-02, ...,
          -2.42295268e-04, -6.04454187e-03, -2.16150304e-01],
         [-2.93892961e-02, -2.55703573e-01, -1.14223479e-01, ...,
          -2.167

In [24]:
clf.intercept_

array([-0.10297981, -0.61278166, -0.25122295,  0.36276882,  0.6042156 ])

In [25]:
index_1 = []
for i in range(0,35):
    if clf.coef_[0][i] > 0.05 :
        index_1.append(i)
print(index_1)
print([name[i] for i in index_1])

[3, 14, 19, 20, 29, 31, 33]
[('orange', 'chicken'), ('soy', 'sauce'), ('sour', 'chicken'), ('white', 'rice'), ('pork', 'fried', 'rice'), ('shrimp', 'fried', 'rice'), ('egg', 'foo', 'young')]


In [27]:
index_2 = []
for i in range(0,35):
    if clf.coef_[1][i] > 0.15:
        index_2.append(i)
print(index_2)
print([name[i] for i in index_2])

[5, 12, 14, 20, 27]
[('pad', 'thai'), ('egg', 'roll'), ('soy', 'sauce'), ('white', 'rice'), ('kung', 'pao', 'chicken')]


In [28]:
index_5 = []
for i in range(0,35):
    if clf.coef_[4][i] < -0.3 :
        index_5.append(i)
print(index_5)
print([name[i] for i in index_5])

[1, 12, 14, 17, 20]
[('dim', 'sum'), ('egg', 'roll'), ('soy', 'sauce'), ('milk', 'tea'), ('white', 'rice')]


In [29]:
from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(n_estimators= 100, random_state=0)

In [30]:
clf2.fit(X,Y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [31]:
index_rf = []
for i in range(0,35):
    if clf2.feature_importances_[i] < 0.015 :
        index_rf.append(i)
print(index_rf)
print([name[i] for i in index_rf])

[24, 32, 34]
[('bubble', 'tea'), ('xiao', 'long', 'bao'), ('dan', 'dan', 'noodles')]


# 3. Fit  in different business

In [135]:
business_id = file["business_id"]

In [33]:
business_index = list(file["business_index"])

In [34]:
dataset = []
labelset = []
for i in range(0,4434):
    data_sub = []
    label_sub = []
    num = 0
    for business in business_index:
        if business == i:
            data_sub.append(data[num])
            label_sub.append(Y[num])
        num += 1
    dataset.append(data_sub)
    labelset.append(label_sub)

In [156]:
#how many restaurants reviews < 10
index_fewreview = []
count = 0
for i in labelset:
    if len(i)<3:
        index_fewreview.append(count)
    count += 1

In [157]:
len(index_fewreview)

0

In [69]:
#let rate 4,5 be 1 and 1,2,3 be 0
label = []
for i in labelset:
    element = []
    for n in i:
        if n>3:
            element.append(1)
        else:
            element.append(0)
    label.append(element)
        

In [100]:
#Experience
X = np.array(dataset[0])
Y = np.array(label[0])
from sklearn.linear_model import LogisticRegressionCV
clf = LogisticRegressionCV(cv=2, random_state=0,multi_class='multinomial').fit(X, Y)

In [101]:
clf.coef_[0]

array([-0.59601777,  0.61226433, -0.41955043,  0.        ,  0.32467737,
        0.        , -0.15005746,  0.        ,  0.78720705,  0.        ,
        0.30882777,  0.        ,  0.        , -0.40429811,  0.        ,
        0.        ,  0.87292006,  0.        ,  0.        ,  1.21858315,
       -0.08405735,  0.        , -0.15005746,  0.87292006,  0.56694641,
        0.        ,  0.        , -0.39772168, -0.36405547,  0.        ,
        1.10779117,  0.        , -0.8413538 ,  0.        ,  0.        ])

In [83]:
index_1 = []
for i in range(0,35):
    if clf.coef_[0][i] > 0.05 :
        index_1.append(i)
print(index_1)
print([name[i] for i in index_1])

35

In [152]:
# give the result of each business
name_high = []
name_low = []
service_with = []

for x,y in zip(dataset, label):
    
    X = np.array(x)
    Y = np.array(y)
    clf = LinearRegression().fit(X,Y)
    #clf = LogisticRegressionCV(cv=2, random_state=0,multi_class='multinomial').fit(X, Y)
    index_max = clf.coef_[1:].argmax()
    name_high.append(name[index_max+1])
    
    index_min = clf.coef_[1:].argmin()
    name_low.append(name[index_min+1])
    
    if clf.coef_[0] < 0:
        service_with.append(1)
        # 1 means service needs to be improved
    else:
        service_with.append(0)
   

In [128]:
name_high[0:10]

[('sour', 'chicken'),
 ('bbq', 'pork'),
 ('egg', 'roll'),
 ('dim', 'sum'),
 ('spring', 'rolls'),
 ('orange', 'chicken'),
 ('egg', 'roll'),
 ('beef', 'noodle', 'soup'),
 ('dim', 'sum'),
 ('wonton', 'soup')]

In [127]:
sum(service_with)

1991

In [137]:
from collections import OrderedDict
business_id = list(OrderedDict.fromkeys(business_id))

In [144]:
import pandas as pd
data = {"business_id":business_id, "high_food": name_high, "low_food" : name_low, "service" : service_with }
df = pd.DataFrame(data)

In [153]:
df.head()

business_id        high_food           low_food  service
0  QXAEGFB4oINsVuTFxEYKFQ  (sour, chicken)  (xiao, long, bao)        1
1  e_EMySqP0uwlVZfd8mRaaQ      (bbq, pork)     (peking, duck)        1
2  44YFU284Z3KDEy25QyVoUw      (egg, roll)       (soy, sauce)        1
3  X8mtoSxY8whtmbDlj0D3Aw       (dim, sum)         (dim, sum)        0
4  MhnihE0alud0ereVInSt8Q  (spring, rolls)       (sour, soup)        1

In [148]:
df.to_csv("Food.csv", encoding="utf-8", index = False)